#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Yuri Sawada 　　　　　
# SPDX-License-Identifier: BSD-3-Clause
import sys

ans = [0,0,1]

for line in sys.stdin:
    try: 
        ans[0] += int(line)   #intは文字列を整数に（失敗すると例外発生）
        ans[1] -= int(line)
        ans[-1] *= int(line)
    except:
        ans[0] += float(line)
        ans[1] -= float(line)
        ans[-1] *= float(line)


print(ans[0])
print(ans[1])
print(ans[-1])
