#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Yuri Sawada 　　　　　
# SPDX-License-Identifier: BSD-3-Clause
import sys

ansa = 0
ansb = 0
ansc = 1

for line in sys.stdin:
    try: 
        ansa += int(line)   #intは文字列を整数に（失敗すると例外発生）
        ansb -= int(line)
        ansc *= int(line)
    except:
        ansa += float(line)
        ansb -= float(line)
        ansc *= float(line)


print("和",ansa)
print("差",ansb)
print("積",ansc)
